"""05. Dummy migration to update genre column to String Array

Revision ID: 06790d1ff81b
Revises: 99f9d5ec97dc
Create Date: 2020-05-02 17:30:41.777061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06790d1ff81b'
down_revision = '99f9d5ec97dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
